### PR TITLE
Fix seqcli user create (#168); add multi-user testing support to the end-to-end tests

### LINKED ISSUE #168: `seqcli user create` fails to set valid role ids
https://github.com/datalust/seqcli/blob/dev/src/SeqCli/Cli/Commands/User/CreateCommand.cs#L127

The user's `RoleIds` collection should contain ... ids. `seqcli user create` is currently sending the title, which will make the user unable to login until a valid role is set in the UI.

### PR DESCRIPTION
**Pull request by nblumhardt**
Fixes #168

To run multi-user tests (we now have one!), supply a valid license through `STDIN`:

```
test\SeqCli.EndToEnd>dotnet run --license-certificate-stdin < Certificate.txt
```

There's a bit of gunk required to get `[CliTestCase(Multiuser = true)]` propagated through Autofac, and argument handling isn't great. I'm out of time now but will come around and take another shot at it down the line :)

### CODE REVIEW

File: src/SeqCli/Cli/Commands/User/CreateCommand.cs [hunk 1]
```diff
@@ -124,7 +124,7 @@ protected override async Task<int> Run()
                     return 1;
                 }
 
-                user.RoleIds.Add(role.Title);
+                user.RoleIds.Add(role.Id);
```
Comment (nblumhardt) [inline src/SeqCli/Cli/Commands/User/CreateCommand.cs:127]: This is the actual fix...

File: test/SeqCli.EndToEnd/User/UserCreateRemoveTestCase.cs [hunk 2]
```diff
@@ -1,48 +1,38 @@
...
-#if MULTIUSER_TESTS
 using System.IO;
-#endif
+using System.Linq;
 
 namespace SeqCli.EndToEnd.User
 {
-    public class UserBasicsTestCase : ICliTestCase
+    [CliTestCase(Multiuser = true)]
+    public class UserCreateRemoveTestCase : ICliTestCase
```
Comment (nblumhardt) [inline test/SeqCli.EndToEnd/User/UserCreateRemoveTestCase.cs:13]: ...and this is the newly-enabled regression test.

**Review by larenelg — APPROVED** [review]

**Comment by nblumhardt** [comment]
The build failure here is https://github.com/dotnet/install-scripts/issues/136 - we'll move this forward so we can get the rest of the 2021.1 release tested and assembled on `dev`.
